version: 1
builder:
  configs:
    - documentation_targets: [Metallic]
      platform: macos
    - documentation_targets: [Metallic]
      platform: ios
    - documentation_targets: [Metallic]
      platform: tvos
    - documentation_targets: [Metallic]
      platform: watchos
